import Link from 'next/link';
import styles from './Home.module.css';

export default function Home() {
  // Use relative paths for assets within the public or handled via build
  // For now, I'll use the absolute path generated by the tool in the props, 
  // but for a real build, they should be in /public. I will copy them later if needed.
  const heroImg = "/hero_modern_hub_premium_1767979123155.png";
  const vanImg = "/safeguarding_van_safespace_1767979144119.png";
  const abstractImg = "/supportive_community_abstract_1767979159722.png";

  return (
    <div className={styles.home}>
      {/* Premium Hero */}
      <section
        className={styles.hero}
        style={{ backgroundImage: `url(${heroImg})` }}
      >
        <div className={styles.heroOverlay} />
        <div className={styles.heroContent}>
          <h1>Welcome to Froggy’s Voice Box</h1>
          <p>
            The central, trauma-informed hub for safeguarding information,
            resources, and survivor-led community connection.
          </p>
          <div className={styles.heroActions}>
            <Link href="/resources" className={styles.btnPrimary}>
              Explore Resources
            </Link>
            <Link href="/about" className={styles.btnSecondary}>
              Our Mission
            </Link>
          </div>
        </div>
      </section>

      {/* Voice Box Intro */}
      <section className={`${styles.section} ${styles.voiceBoxSection}`}>
        <div className={styles.container}>
          <div className={styles.sectionContent}>
            <div className={styles.textContent}>
              <h2>A Sanctuary for Information</h2>
              <p>
                Froggy’s Voice Box is designed to be an emotionally safe space where
                families, survivors, and professionals can access clear, non-triggering
                guidance.
              </p>
              <div className={styles.traumaAccent}>
                "The way a child shows abuse is as important as the abuse itself.
                We provide the tools to listen properly."
              </div>
              <p>
                Our hub brings together community outreach, mobile safe-spaces, and
                educational resources to ensure no disclosure goes unheard.
              </p>
            </div>
            <div
              className={styles.imageBox}
              style={{ backgroundImage: `url(${abstractImg})` }}
            />
          </div>
        </div>
      </section>

      {/* Froggy's Law Intro */}
      <section className={`${styles.section} ${styles.altSection}`}>
        <div className={styles.container}>
          <div className={styles.sectionContent}>
            <div
              className={`${styles.imageBox} ${styles.orderMobile}`}
              style={{ backgroundImage: `url(${vanImg})` }}
            />
            <div className={styles.textContent}>
              <h2>The Reform: Froggy’s Law</h2>
              <p>
                Behind our community hub is a robust model for national structural reform.
                Froggy’s Law creates a mandated, five-step safeguarding pathway.
              </p>
              <p>
                By moving away from ad-hoc responses and towards a trauma-informed standard,
                we ensure that every adult in a child's life knows how to respond with
                clarity and care.
              </p>
              <Link href="/reform" className={styles.btnGentle} style={{ background: 'var(--calm-blue)', color: 'white' }}>
                Learn About the Reform Model
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Final Impact CTA */}
      <section className={styles.supportSection}>
        <div className={styles.container}>
          <div className={styles.supportContent}>
            <h2>Together, We Create Change</h2>
            <p>
              Join the growing movement for safer communities. Whether you're a professional
              looking for training or a supporter wanting to help us reach more children.
            </p>
            <div className={styles.heroActions}>
              <Link href="/support" className={styles.btnPrimary}>
                Support Our Work
              </Link>
              <Link href="/training" className={styles.btnSecondary}>
                Professional Training
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
